SOURCES = \
	src/AbstractSet.php \
	src/AvlTree.php \
	src/BinarySearchTree.php \
	src/BinaryTree.php \
	src/Collection.php \
	src/EmptyGuard.php \
	src/Enumerable.php \
	src/Enumerator.php \
	src/Exception/DomainException.php \
	src/Exception/EmptyException.php \
	src/Exception/Exception.php \
	src/Exception/FullException.php \
	src/Exception/FunctionException.php \
	src/Exception/IndexException.php \
	src/Exception/KeyException.php \
	src/Exception/LookupException.php \
	src/Exception/StateException.php \
	src/Exception/TypeException.php \
	src/function.php \
	src/HashMap.php \
	src/HashSet.php \
	src/Iterator/ArrayIterator.php \
	src/Iterator/BinaryTreeIterator.php \
	src/Iterator/CountableIterator.php \
	src/Iterator/CountableSeekableIterator.php \
	src/Iterator/FilteringIterator.php \
	src/Iterator/HashMapIterator.php \
	src/Iterator/HashSetIterator.php \
	src/Iterator/InOrderIterator.php \
	src/Iterator/IteratorCollection.php \
	src/Iterator/IteratorCollectionAdapter.php \
	src/Iterator/KeyIterator.php \
	src/Iterator/LevelOrderIterator.php \
	src/Iterator/LimitingIterator.php \
	src/Iterator/LinkedQueueIterator.php \
	src/Iterator/LinkedStackIterator.php \
	src/Iterator/MapIterator.php \
	src/Iterator/MappingIterator.php \
	src/Iterator/PostOrderIterator.php \
	src/Iterator/PreOrderIterator.php \
	src/Iterator/QueueIterator.php \
	src/Iterator/SeekableIterator.php \
	src/Iterator/SetIterator.php \
	src/Iterator/SkippingIterator.php \
	src/Iterator/SlicingIterator.php \
	src/Iterator/SortedMapIterator.php \
	src/Iterator/SortedSetIterator.php \
	src/Iterator/StackIterator.php \
	src/Iterator/ValueIterator.php \
	src/Iterator/VectorIterator.php \
	src/LinkedDataNode.php \
	src/LinkedList.php \
	src/LinkedNode.php \
	src/LinkedQueue.php \
	src/LinkedStack.php \
	src/LinkedTerminalNode.php \
	src/Map.php \
	src/Pair.php \
	src/Queue.php \
	src/Set.php \
	src/SortedMap.php \
	src/SortedSet.php \
	src/Stack.php \
	src/Vector.php
