# Sources are in order such that sequentially loading them fully loads the
# library without triggering the autoloading mechanism
SOURCES = \
	src/Collection/function.php \
	Ardent/Enumerable.php \
	Ardent/Optional.php \
	src/Collection/Pair.php \
	src/Collection/Collection.php \
	src/Collection/Enumerator.php \
	src/Collection/Enumerable.php \
	src/Collection/SetIterator.php \
	src/Collection/Set.php \
	src/Collection/MapIterator.php \
	src/Collection/Map.php \
	src/Collection/QueueIterator.php \
	src/Collection/Queue.php \
	src/Collection/StackIterator.php \
	src/Collection/Stack.php \
	src/Collection/OuterIteratorTrait.php \
	src/Collection/BinaryTreeIterator.php \
	src/Collection/BinaryTree.php \
	src/Collection/BinarySearchTree.php \
	src/Collection/InOrderIterator.php \
	src/Collection/LevelOrderIterator.php \
	src/Collection/PostOrderIterator.php \
	src/Collection/PreOrderIterator.php \
	src/Collection/AvlTree.php \
	src/Collection/ArrayIterator.php \
	src/Collection/AbstractSet.php \
	src/Collection/SortedSetIterator.php \
	src/Collection/SortedSet.php \
	src/Collection/HashSetIterator.php \
	src/Collection/HashSet.php \
	src/Collection/HashMapIterator.php \
	src/Collection/HashMap.php \
	src/Collection/LinkedNode.php \
	src/Collection/LinkedDataNode.php \
	src/Collection/LinkedTerminalNode.php \
	src/Collection/LinkedList.php \
	src/Collection/LinkedQueueIterator.php \
	src/Collection/LinkedQueue.php \
	src/Collection/LinkedStackIterator.php \
	src/Collection/LinkedStack.php \
	src/Collection/SortedMapIterator.php \
	src/Collection/SortedMap.php \
